version: '3.8'

######################################
# SERVICES
######################################

services:

  ######################################
  # DATABASES
  ######################################

  # MONGODB
  arcen-mongodb:
    image: mongo:latest
    container_name: arcen-mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: arcen
      MONGO_INITDB_ROOT_PASSWORD: arcen
    volumes:
      - arcen_db_mongodb:/data/db
    ports:
      - '27017:27017'


  # POSTGRESQL
  arcen-postgresql:
    image: postgres:alpine
    container_name: arcen-postgresql
    environment:
      - POSTGRES_USER=arcen
      - POSTGRES_PASSWORD=arcen
      - POSTGRES_DB=arcen
    ports:
      - '5432:5432'
    volumes: 
      - arcen_db_postgresql:/var/lib/postgresql/data/


  ######################################
  # MICROSERVICES
  ######################################

  # AUDIT
  arcen-service-audit:
    build: ./service-audit
    container_name: arcen-service-audit
    environment:
      - MONGODB_CONNSTRING=mongodb://arcen:arcen@arcen-mongodb:27017/
      - MONGODB_DB=arcen_audit
      - MONGODB_HOST=arcen-postgresql-host
      - MONGODB_PORT=27017
    depends_on:
      - arcen-mongodb
    restart: always
    ports: 
      - "8001:8001"


  # BOX
  arcen-service-box-storage:
    build: ./service-box-storage
    container_name: arcen-service-box-storage
    environment:
      - POSTGRESQL_CONNSTRING=postgresql://arcen:arcen@arcen-postgresql:5432/arcen
      - POSTGRESQL_DB=arcen
      - POSTGRESQL_HOST=arcen-postgresql-host
      - POSTGRESQL_PORT=5432
      - ARCEN_ENDPOINT_SERVICE_AUDIT=arcen-service-audit-host
    depends_on:
      - arcen-postgresql
      - arcen-service-audit
    restart: always
    ports: 
      - "8002:8002"
      

  # DIGITIZATION
  arcen-service-digitization:
    build: ./service-digitization
    container_name: arcen-service-digitization
    environment:
      - MONGODB_CONNSTRING=mongodb://arcen:arcen@arcen-mongodb:27017/
      - MONGODB_DB=arcen_audit
      - MONGODB_HOST=arcen-postgresql-host
      - MONGODB_PORT=27017
      - FEIGN_ARCEN=http://arcen-service-audit:8001/api/audit
      - FEIGN_ARCEN_SAVE=/
    depends_on:
      - arcen-mongodb
      - arcen-service-audit
    restart: always
    ports: 
      - "8003:8003"

  
  # FURNITURE STORAGE
  arcen-service-furniture-storage:
    build: ./service-furniture-storage
    container_name: arcen-service-furniture-storage
    environment:
      - POSTGRESQL_CONNSTRING=postgresql://arcen:arcen@arcen-postgresql:5432/arcen
      - POSTGRESQL_DB=arcen
      - POSTGRESQL_HOST=arcen-postgresql-host
      - POSTGRESQL_PORT=5432
      - ARCEN_ENDPOINT_SERVICE_AUDIT=arcen-service-audit-host
    depends_on:
      - arcen-postgresql
      - arcen-service-audit
    restart: always
    ports: 
      - "8004:8004"


  # OBJECT STORAGE
  arcen-service-object-storage:
    build: ./service-object-storage
    container_name: arcen-service-object-storage
    environment:
      - POSTGRESQL_CONNSTRING=postgresql://arcen:arcen@arcen-postgresql:5432/arcen
      - POSTGRESQL_DB=arcen
      - POSTGRESQL_HOST=arcen-postgresql-host
      - POSTGRESQL_PORT=5432
      - FEIGN_ARCEN=http://arcen-service-audit:8001/api/audit
      - FEIGN_ARCEN_SAVE=/
    depends_on:
      - arcen-postgresql
      - arcen-service-audit
    restart: always
    ports: 
      - "8005:8005"
 
  
  # SHELF STORAGE
  arcen-service-shelf-storage:
    build: ./service-shelf-storage
    container_name: arcen-service-shelf-storage
    environment:
      - POSTGRESQL_CONNSTRING=postgresql://arcen:arcen@arcen-postgresql:5432/arcen
      - POSTGRESQL_DB=arcen
      - POSTGRESQL_HOST=arcen-postgresql-host
      - POSTGRESQL_PORT=5432
      - ARCEN_ENDPOINT_SERVICE_AUDIT=arcen-service-audit-host
      - FURNITURE_SERVICE_HOST_URL=http://arcen-service-furniture-storage:8004/api/furniture
    depends_on:
      - arcen-postgresql
      - arcen-service-audit
    restart: always
    ports: 
      - "8008:8008"

  
  # USER
  arcen-service-user:
    build: ./service-user
    container_name: arcen-service-user
    environment:
      - POSTGRESQL_CONNSTRING=postgresql://arcen:arcen@arcen-postgresql:5432/arcen
      - POSTGRESQL_DB=arcen
      - POSTGRESQL_HOST=arcen-postgresql-host
      - POSTGRESQL_PORT=5432
      - ARCEN_ENDPOINT_SERVICE_AUDIT=arcen-service-audit-host
    depends_on:
      - arcen-postgresql
      - arcen-service-audit
    restart: always
    ports: 
      - "8009:8009"

  arcen-nginx-reverse-proxy:
    image: nginx:latest
    container_name: arcen-nginx
    ports:
      - 8080:8080
    volumes:
      - ./nginx_config.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - arcen-mongodb
      - arcen-postgresql
      - arcen-service-audit
      - arcen-service-box-storage
      - arcen-service-digitization
      - arcen-service-furniture-storage
      - arcen-service-object-storage
      - arcen-service-shelf-storage
      - arcen-service-user



######################################
# VOLUMEN
######################################

volumes:
  arcen_db_mongodb: {}
  arcen_db_postgresql: {}

######################################
# NETWORK
######################################

    
