version: '3.8'

######################################
# SERVICES
######################################

services:

  ######################################
  # DATABASES
  ######################################

  # MONGODB
  arcen-mongodb:
    image: mongo:latest
    container_name: arcen-mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: arcen
      MONGO_INITDB_ROOT_PASSWORD: arcen
    volumes:
      - arcen_db_mongodb:/data/db
    ports:
      - '27017:27017'

  # POSTGRESQL
  arcen-postgresql:
    image: postgres:alpine
    container_name: arcen-postgresql
    environment:
      - POSTGRES_USER=arcen
      - POSTGRES_PASSWORD=arcen
      - POSTGRES_DB=arcen
      - APP_DB_USER=arcen
      - APP_DB_PASS=arcen
      - APP_DB_NAME=arcen
    ports:
      - '5432:5432'
    volumes: 
      - arcen_db_postgresql:/var/lib/postgresql/data/
      #- ../db-postgresql:/docker-entrypoint-initdb.d/

  ######################################
  # MICROSERVICES
  ######################################

  # AUDIT
  arcen-service-audit:
    build: ./service-audit
    container_name: arcen-service-audit
    environment:
      - MONGODB_CONNSTRING=mongodb://arcen:arcen@arcen-mongodb:27017/
      - MONGODB_DB=arcen_audit
      - MONGODB_HOST=arcen-postgresql-host
      - MONGODB_PORT=27017
    depends_on:
      - arcen-mongodb
    restart: always
    ports: 
      - "8001:8001"

    # DIGITIZATION
  arcen-service-digitization:
    build: ./service-digitization
    container_name: arcen-service-digitization
    environment:
      - MONGODB_CONNSTRING=mongodb://arcen:arcen@arcen-mongodb:27017/
      - MONGODB_DB=arcen_audit
      - MONGODB_HOST=arcen-postgresql-host
      - MONGODB_PORT=27017
      - FEIGN_ARCEN=http://arcen-service-audit:8001/api/audit
      - FEIGN_ARCEN_SAVE=/
      - APP_PATH_TMP_IMAGE_SEPARATOR=/
      - APP_PATH_TMP_IMAGE=tmp
      - APP_PATH_PDF=pdf
    depends_on:
      - arcen-mongodb
      - arcen-service-audit
    restart: always
    ports: 
      - "8003:8003"
######################################
# VOLUMEN
######################################

volumes:
  arcen_db_mongodb: {}
  arcen_db_postgresql: {}

    
