version: '3.8'

######################################
# SERVICES
######################################

services:

  ######################################
  # DATABASES
  ######################################

  # MONGODB
  arcen-mongodb:
    image: mongo:latest
    container_name: arcen-mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: arcen
      MONGO_INITDB_ROOT_PASSWORD: arcen
    volumes:
      - arcen_db_mongodb:/data/db
    ports:
      - '27017:27017'

  # POSTGRESQL
  arcen-postgresql:
    image: postgres:alpine
    container_name: arcen-postgresql
    environment:
      - POSTGRES_USER=arcen
      - POSTGRES_PASSWORD=arcen
      - POSTGRES_DB=arcen
      - APP_DB_USER=arcen
      - APP_DB_PASS=arcen
      - APP_DB_NAME=arcen
    ports:
      - '5432:5432'
    volumes: 
      #- arcen_db_postgresql:/var/lib/postgresql/data/
      - ../db-postgresql:/docker-entrypoint-initdb.d/

  ######################################
  # MICROSERVICES
  ######################################

  # AUDIT
  arcen-service-audit:
    build: ./service-audit
    container_name: arcen-service-audit
    environment:
      - MONGODB_CONNSTRING=mongodb://arcen:arcen@arcen-mongodb:27017/
      - MONGODB_DB=arcen_audit
      - MONGODB_HOST=arcen-postgresql-host
      - MONGODB_PORT=27017
    depends_on:
      - arcen-mongodb
    restart: always
    ports: 
      - "8001:8001"

  # BOX
  ##1##arcen-service-box-storage:
    ##1##build: ./service-box-storage
    ##1##container_name: arcen-service-box-storage
    ##1##environment:
      ##1##- POSTGRESQL_CONNSTRING=postgresql://arcen:arcen@arcen-postgresql:5432/arcen
      ##1##- POSTGRESQL_DB=arcen
      ##1##- POSTGRESQL_HOST=arcen-postgresql-host
      ##1##- POSTGRESQL_PORT=5432
      ##1##- ARCEN_ENDPOINT_SERVICE_AUDIT=arcen-service-audit-host
    ##1##depends_on:
      ##1##- arcen-postgresql
      ##1##- arcen-service-audit
    ##1##restart: always
    ##1##ports: 
      ##1##- "8002:8002"   
      
  # FURNITURE STORAGE
  arcen-service-furniture-storage:
    build: ./service-furniture-storage
    container_name: arcen-service-furniture-storage
    environment:
        - POSTGRESQL_CONNSTRING=postgresql://arcen:arcen@arcen-postgresql:5432/arcen
        - POSTGRESQL_DB=arcen
        - POSTGRESQL_HOST=arcen-postgresql-host
        - POSTGRESQL_PORT=5432
        - FEIGN_ARCEN=http://arcen-service-audit:8001/api/audit
        - FEIGN_ARCEN_SAVE=/
    depends_on:
      - arcen-postgresql
      - arcen-service-audit
    restart: always
    ports: 
      - "8004:8004"
      
######################################
# VOLUMEN
######################################

volumes:
  arcen_db_mongodb: {}
  arcen_db_postgresql: {}

    
