# UVICORN
APP_UVICORN_NAME= "main:app"
APP_UVICORN_HOST = "http://127.0.0.1/"
APP_UVICORN_PORT = 4000
APP_UVICORN_LOG = "info"

# ENDPOINT
ENDPOINT_APP = "/api"
ENDPOINT_APP_DEPENDENCE = "/dependence"
ENDPOINT_APP_SHELF = "/shelf"
ENDPOINT_APP_TYPE_SHELF = "/type-shelf"

ENDPOINT_GENERIC_FIND_BY_ID = "/{id}"
ENDPOINT_GENERIC_FIND_ALL = "/"
ENDPOINT_GENERIC_SAVE = "/"
ENDPOINT_GENERIC_UPDATE= "/{id}"
ENDPOINT_GENERIC_DELETE_BY_ID = "/{id}"

# DATABASE VARS
DATABASE_POSTGRESQL_USER = "arcen";
DATABASE_POSTGRESQL_PASSWORD = "arcen";
DATABASE_POSTGRESQL_HOST = "localhost";
DATABASE_POSTGRESQL_PORT = "";
DATABASE_POSTGRESQL_DATABASE = "arcen_shelf";

# DATABASE CONNECT
DATABASE_POSTGRESQL_URL = "postgresql://{0}:{1}@{2}{3}/{4}".format(
    DATABASE_POSTGRESQL_USER,
    DATABASE_POSTGRESQL_PASSWORD,
    DATABASE_POSTGRESQL_HOST,
    DATABASE_POSTGRESQL_PORT,
    DATABASE_POSTGRESQL_DATABASE
)

# DATABASE TABLE
DATABASE_POSTGRESQL_TABLE_DEPENDENCE = "dependence"
DATABASE_POSTGRESQL_TABLE_SHELF = "shelf"
DATABASE_POSTGRESQL_TABLE_TYPE_SHELF = "type_shelf"

# COLUMNA DEPENDENCE
COLUMN_DEPENDENCE = "dependence"
COLUMN_DEPENDENCE_ID = "id"
COLUMN_DEPENDENCE_NAME = "name"
COLUMN_DEPENDENCE_CODE = "code"

# COLUMNA SHELF
COLUMN_SHELF = "shelf"
COLUMN_SHELF_ID = "id"
COLUMN_SHELF_ID_DEPENDENCE = "id_dependence"
COLUMN_SHELF_ID_TYPE_SHELF = "id_type_shelf"
COLUMN_SHELF_ID_FURNITURE = "id_furniture"
COLUMN_SHELF_NUMBER_SHELF = "number_shelf"
COLUMN_SHELF_CREATION_DATE = "date"

# COLUMNA TYPE SHELF
COLUMN_TYPE_SHELF = "type_shelf"
COLUMN_TYPE_SHELF_ID = "id"
COLUMN_TYPE_SHELF_NUMBER_TYPE_SHELF = "number_type_shelf"
COLUMN_TYPE_SHELF_DEPTH = "depth"
COLUMN_TYPE_SHELF_HEIGHT = "height"
COLUMN_TYPE_SHELF_WIDTH= "width"
COLUMN_TYPE_SHELF_CREATION_DATE = "date"
