DATABASE_MONGODB_USER = "prince:<password>@cluster0.xfinu";
DATABASE_MONGODB_URL = "mongodb+srv://"+DATABASE_MONGODB_USER+".mongodb.net/";
DATABASE_MONGODB_NAME = "audit";
DATABASE_MONGODB_NAME_TABLE = "audit";
DATABASE_MONGODB_PERMISSION = "?retryWrites=true&w=majority";
DATABASE_MONGODB = DATABASE_MONGODB_URL +DATABASE_MONGODB_NAME + DATABASE_MONGODB_PERMISSION;