# DATABASE
DATABASE_MONGODB_USER = "arcen:arcen";
DATABASE_MONGODB_CLUSTER = "@cluster0.qahfe.mongodb.net";
DATABASE_MONGODB_URL = "mongodb+srv://"+DATABASE_MONGODB_USER+DATABASE_MONGODB_CLUSTER+"/test";
DATABASE_MONGODB_NAME = "arcen_audit";
DATABASE_MONGODB_NAME_TABLE = "audit";
DATABASE_MONGODB = DATABASE_MONGODB_URL +DATABASE_MONGODB_NAME;

# COLUMNA DATABASE
COLUMN_AUDIT_NAME = "audit"
COLUMN_AUDIT_ID_NAME = "_id"
COLUMN_AUDIT_ID_TWO_NAME = "id"
COLUMN_AUDIT_SERVICE_NAME = "service"
COLUMN_AUDIT_OPERATION_NAME = "operation"
COLUMN_AUDIT_ID_USER_NAME = "id_user"
COLUMN_AUDIT_RESPONSE_NAME = "response"
COLUMN_AUDIT_DATE_NAME = "date"

# FORMAT
FORMAT_DATE = '%Y-%m-%d %H:%M'