# UVICORN
APP_UVICORN_NAME= "main:app"
APP_UVICORN_HOST = "http://127.0.0.1/"
APP_UVICORN_PORT = 4000
APP_UVICORN_LOG = "info"

# ENDPOINT
ENDPOINT_APP = "/api"
ENDPOINT_APP_BLOCK = "/block"
ENDPOINT_APP_FURNITURE = "/furniture"
ENDPOINT_APP_TYPE_FURNITURE = "/type-furniture"

ENDPOINT_GENERIC_FIND_BY_ID = "/{id}"
ENDPOINT_GENERIC_FIND_ALL = "/"
ENDPOINT_GENERIC_SAVE = "/"
ENDPOINT_GENERIC_UPDATE= "/{id}"
ENDPOINT_GENERIC_DELETE_BY_ID = "/{id}"

# DATABASE VARS
DATABASE_POSTGRESQL_USER = "arcen";
DATABASE_POSTGRESQL_PASSWORD = "arcen";
DATABASE_POSTGRESQL_HOST = "arcen";
DATABASE_POSTGRESQL_PORT = "arcen";
DATABASE_POSTGRESQL_DATABASE = "arcen";

# DATABASE CONNECT
DATABASE_POSTGRESQL_URL = "postgresql://{0}:{1}@{2}:{3}/{4}".format(
    DATABASE_POSTGRESQL_USER,
    DATABASE_POSTGRESQL_PASSWORD,
    DATABASE_POSTGRESQL_HOST,
    DATABASE_POSTGRESQL_PORT,
    DATABASE_POSTGRESQL_DATABASE
)

# DATABASE TABLE
DATABASE_POSTGRESQL_TABLE_BLOCK = "block"
DATABASE_POSTGRESQL_TABLE_FURNITURE = "furniture"
DATABASE_POSTGRESQL_TABLE_TYPE_FURNITURE = "type_furniture"

# COLUMNA DATABASE
COLUMN_AUDIT_NAME = "audit"
COLUMN_AUDIT_ID_NAME = "_id"
COLUMN_AUDIT_ID_TWO_NAME = "id"
COLUMN_AUDIT_SERVICE_NAME = "service"
COLUMN_AUDIT_OPERATION_NAME = "operation"
COLUMN_AUDIT_ID_USER_NAME = "id_user"
COLUMN_AUDIT_RESPONSE_NAME = "response"
COLUMN_AUDIT_DATE_NAME = "date"

# FORMAT
FORMAT_DATE = '%Y-%m-%d %H:%M'