# ENDPOINT
ENDPOINT_APP = "/api"
ENDPOINT_APP_OBJECT = "/object"
ENDPOINT_APP_SUB_OBJECT = "/sub-object"
ENDPOINT_APP_TYPE_OBJECT = "/type-object"

ENDPOINT_GENERIC_FIND_BY_ID = "/{id}"
ENDPOINT_GENERIC_FIND_ALL = "/"
ENDPOINT_GENERIC_SAVE = "/"
ENDPOINT_GENERIC_UPDATE= "/{id}"
ENDPOINT_GENERIC_DELETE_BY_ID = "/{id}"

# DATABASE VARS
DATABASE_POSTGRESQL_USER = "arcen";
DATABASE_POSTGRESQL_PASSWORD = "arcen";
DATABASE_POSTGRESQL_HOST = "localhost";
DATABASE_POSTGRESQL_PORT = "";
DATABASE_POSTGRESQL_DATABASE = "arcen_object";

# DATABASE CONNECT
DATABASE_POSTGRESQL_URL = "postgresql://arcen:arcen@arcen-postgresql:5432/arcen"

# DATABASE TABLE
DATABASE_POSTGRESQL_TABLE_OBJECT = "object"
DATABASE_POSTGRESQL_TABLE_SUB_OBJECT= "sub_object"
DATABASE_POSTGRESQL_TABLE_TYPE_OBJECT = "type_object"

# COLUMNA OBJECT
COLUMN_OBJECT = "object"
COLUMN_OBJECT_ID = "id"
COLUMN_OBJECT_ID_TYPE_OBJECT = "id_type_object"
COLUMN_OBJECT_ID_SUB_OBJECT = "id_sub_object"
COLUMN_OBJECT_CREATION_DATE = "date"

# COLUMNA SUB_OBJECT
COLUMN_SUB_OBJECT = "sub_object"
COLUMN_SUB_OBJECT_ID = "id"
COLUMN_SUB_OBJECT_NUMBER = "number"
COLUMN_SUB_OBJECT_BOX = "box"
COLUMN_SUB_OBJECT_CREATION_DATE = "date"

# COLUMNA TYPE_OBJECT
COLUMN_TYPE_OBJECT = "type_object"
COLUMN_TYPE_OBJECT_ID = "id"
COLUMN_TYPE_OBJECT_NAME = "name"
COLUMN_TYPE_OBJECT_HEIGHT = "height"
COLUMN_TYPE_OBJECT_WIDTH = "width"
COLUMN_TYPE_OBJECT_DEPTH = "depth"
COLUMN_TYPE_OBJECT_CREATION_DATE = "date"
