# FORMAT
FORMAT_DATE = '%Y-%m-%d %H:%M'

# ENDPOINT
ENDPOINT_APP = "/api"
ENDPOINT_APP_DOCUMENT = "/document"
ENDPOINT_APP_DOCUMENT_LOCATION = "/document-location"
ENDPOINT_APP_DOCUMENT_VERSION = "/document-version"
ENDPOINT_APP_INVOICE = "/invoice"
ENDPOINT_APP_INVOICE_STATUS = "/invoice-status"

ENDPOINT_GENERIC_FIND_BY_ID = "/{id}"
ENDPOINT_GENERIC_FIND_ALL = "/"
ENDPOINT_GENERIC_SAVE = "/"
ENDPOINT_GENERIC_UPDATE= "/{id}"
ENDPOINT_GENERIC_DELETE_BY_ID = "/{id}"

# DATABASE
DATABASE_MONGODB_USER = "arcen:arcen";
DATABASE_MONGODB_CLUSTER = "@cluster0.qahfe.mongodb.net";
DATABASE_MONGODB_URL = "mongodb+srv://"+DATABASE_MONGODB_USER+DATABASE_MONGODB_CLUSTER+"/";
DATABASE_MONGODB_DB = "arcen_digitization";
DATABASE_MONGODB_TABLE = "digitization";
DATABASE_MONGODB = DATABASE_MONGODB_URL +DATABASE_MONGODB_DB;

# DATABASE TABLE
DATABASE_MONGODB_TABLE_DOCUMENT = "document"
DATABASE_MONGODB_TABLE_DOCUMENT_VERSION = "document_version"
DATABASE_MONGODB_TABLE_DOCUMENT_LOCATION = "document_location"
DATABASE_MONGODB_TABLE_INVOICE = "invoice"
DATABASE_MONGODB_TABLE_INVOICE_STATUS = "invoice_status"

# COLUMNA TABLE DOCUMENT
COLUMN_DOCUMENT = DATABASE_MONGODB_TABLE_DOCUMENT
COLUMN_DOCUMENT_ID = "_id"
COLUMN_DOCUMENT_ID_TWO = "id"
COLUMN_DOCUMENT_ID_DOCUEMNT_LOCATION = "id_document_location"
COLUMN_DOCUMENT_NAME = "name"
COLUMN_DOCUMENT_BASE64 = "document"
COLUMN_DOCUMENT_PATH_DOCUMENT_LOCAL = "path_document"
COLUMN_DOCUMENT_DATE = "date"

# COLUMNA TABLE DOCUMENT LOCATION
COLUMN_DOCUMENT_LOCATION = DATABASE_MONGODB_TABLE_DOCUMENT_LOCATION
COLUMN_DOCUMENT_LOCATION_ID = "_id"
COLUMN_DOCUMENT_LOCATION_ID_TWO = "id"
COLUMN_DOCUMENT_LOCATION_NAME = "name"
COLUMN_DOCUMENT_LOCATION_ID_OBJECT = "id_object"
COLUMN_DOCUMENT_LOCATION_ID_INVOICE = "id_invoice"
COLUMN_DOCUMENT_LOCATION_DATE = "date"

# COLUMNA TABLE DOCUMENT VERSION
COLUMN_DOCUMENT_VERSION = DATABASE_MONGODB_TABLE_DOCUMENT_VERSION
COLUMN_DOCUMENT_VERSION_ID = "_id"
COLUMN_DOCUMENT_VERSION_ID_TWO = "id"
COLUMN_DOCUMENT_VERSION_ID_DOCUMENT_LOCATION = "id_document_location"
COLUMN_DOCUMENT_VERSION_VERSION = "version"
COLUMN_DOCUMENT_VERSION_DATE = "date"

# COLUMNA TABLE INVOICE
COLUMN_INVOICE = DATABASE_MONGODB_TABLE_INVOICE
COLUMN_INVOICE_ID = "_id"
COLUMN_INVOICE_ID_TWO = "id"
COLUMN_INVOICE_NAME = "name"
COLUMN_INVOICE_INDEX_NUMBER = "index_number"
COLUMN_INVOICE_ID_INVOICE_STATU = "id_invoice_statu"
COLUMN_INVOICE_SECURITY_LEVEL = "security_level"
COLUMN_INVOICE_DATE = "date"

# COLUMNA TABLE INVOICE STATUS
COLUMN_INVOICE_STATUS = DATABASE_MONGODB_TABLE_INVOICE_STATUS
COLUMN_INVOICE_STATUS_ID = "_id"
COLUMN_INVOICE_STATUS_ID_TWO = "id"

# FEIGN
FEIGN_TYPE_POST = "POST"
FEIGN_TYPE_GET = "GET"
FEIGN_TYPE_PUT = "PUT"
FEIGN_TYPE_DELETE = "DELETE"

FEIGN_ENDPOINT = "endpoint"
FEIGN_ENDPOINT_AUDIT = "http://127.0.0.1:81/api/audit"
FEIGN_ENDPOINT_AUDIT_SAVE = "/"

# RESPONSE STATUS
RESPONSE_STATUS_CODE_GET = 200
RESPONSE_STATUS_CODE_POST = 201
RESPONSE_STATUS_CODE_PUT = 202
RESPONSE_STATUS_CODE_DELETE = 204

RESPONSE_STATUS_CODE_GENERIC_FIND_ALL = RESPONSE_STATUS_CODE_GET
RESPONSE_STATUS_CODE_GENERIC_FIND_BY_ID = RESPONSE_STATUS_CODE_GET
RESPONSE_STATUS_CODE_GENERIC_FIND_BY_ID_NOT_CONTENT = 424
RESPONSE_STATUS_CODE_GENERIC_DELETE_BY_ID = RESPONSE_STATUS_CODE_DELETE
RESPONSE_STATUS_CODE_GENERIC_DELETE_BY_ID_NOT_CONTENT = 418
RESPONSE_STATUS_CODE_GENERIC_SAVE = RESPONSE_STATUS_CODE_POST
RESPONSE_STATUS_CODE_GENERIC_SAVE_ERROR_SAVE = 423
RESPONSE_STATUS_CODE_GENERIC_UPDATE = RESPONSE_STATUS_CODE_PUT
RESPONSE_STATUS_CODE_GENERIC_UPDATE_NOT_CONTENT = 424
RESPONSE_STATUS_CODE_GENERIC_PERSISTENCE_ERROR = 427

RESPONSE_STATUS_CODE_AUDIT_ERROR_SAVE = 423

# RESPONSE MSG
RESPONSE_MSG_GENERIC_PERSISTENCE_ERROR = "Se ha presentado un error. No eres tu, somos nosotros!"

RESPONSE_MSG_DOCUMENT_FIND_BY_ID_NOT_CONTENT =  "¡Ups! verifique el id del documento, no encontramos ningun resultado."
RESPONSE_MSG_DOCUMENT_SAVE_ERROR_SAVE = "¡Ups! no hemos podido guardar el documento."

RESPONSE_MSG_DOCUMENT_LOCATION_FIND_BY_ID_NOT_CONTENT =  "¡Ups! verifique el id de la ubicacion del documento, no encontramos ningun resultado."
RESPONSE_MSG_DOCUMENT_LOCATION_SAVE_ERROR_SAVE = "¡Ups! no hemos podido guardar la ubicacion del documento."

RESPONSE_MSG_DOCUMENT_VERSION_FIND_BY_ID_NOT_CONTENT =  "¡Ups! verifique el id de la version del documento, no encontramos ningun resultado."
RESPONSE_MSG_DOCUMENT_VERSION_SAVE_ERROR_SAVE = "¡Ups! no hemos podido guardar la version del documento."

# RESPONSE MODEL
RESPONSE_MODEL_DOCUMENT_FIND_ALL = list
RESPONSE_MODEL_DOCUMENT_DELETE_BY_ID = bool

RESPONSE_MODEL_DOCUMENT_VERSION_FIND_ALL = list
RESPONSE_MODEL_DOCUMENT_VERSION_DELETE_BY_ID = bool

RESPONSE_MODEL_DOCUMENT_LOCATION_FIND_ALL = list
RESPONSE_MODEL_DOCUMENT_LOCATION_DELETE_BY_ID = bool

RESPONSE_MODEL_INVOICE_FIND_ALL = list
RESPONSE_MODEL_INVOICE_DELETE_BY_ID = bool

RESPONSE_MODEL_INVOICE_STATUS_FIND_ALL = list
RESPONSE_MODEL_INVOICE_STATUS_DELETE_BY_ID = bool

# AUDIT
AUDIT_DOCUMENT_SERVICE = "DOCUMENT"
AUDIT_DOCUMENT_OPERATION_SAVE = "SAVE"
AUDIT_DOCUMENT_OPERATION_UPDATE = "UPDATE"
AUDIT_DICUMENT_OPERATION_DELETE_BY_ID = "DELETE_BY_ID"

AUDIT_DOCUMENT_LOCATION_SERVICE = "DOCUMENT_LOCATION"
AUDIT_DOCUMENT_LOCATION_OPERATION_SAVE = "SAVE"
AUDIT_DOCUMENT_LOCATION_OPERATION_UPDATE = "UPDATE"
AUDIT_DICUMENT_LOCATION_OPERATION_DELETE_BY_ID = "DELETE_BY_ID"

AUDIT_DOCUMENT_VERSION_SERVICE = "DOCUMENT_VERSION"
AUDIT_DOCUMENT_VERSION_OPERATION_SAVE = "SAVE"
AUDIT_DOCUMENT_VERSION_OPERATION_UPDATE = "UPDATE"
AUDIT_DICUMENT_VERSION_OPERATION_DELETE_BY_ID = "DELETE_BY_ID"

# DATA
DATA_REMOVE = "isRemove"
DATA_REMOVE_VALUE_DEFAULT = False
DATA_COMMON_ERROR_CODE = "code"
DATA_COMMON_ERROR_MSG = "message"